#!/bin/bash

pip install -r requirements.txt

op=$1
if [[ "$op" = "-t" ]]; then
    # build to stable
    dst=src/proxy_server_test.c
else
    # build to test
    dst=src/proxy_server_stable.c
fi

src=proxy_server.c

cp "$src" "$dst"

cat << EOF > CMakeLists.txt
cmake_minimum_required(VERSION 3.12)

project(PQC_SERVER)

if(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE Debug)
endif()

find_package(OpenSSL REQUIRED)

include_directories(\${OPENSSL_INCLUDE_DIR})
include_directories(\${CMAKE_SOURCE_DIR}/include)

add_subdirectory(kyber)
add_subdirectory(crypto)
add_subdirectory(server)
add_subdirectory(tls)


set(SOURCE_FILES $dst)

add_executable(
    test_server
    
    \${SOURCE_FILES}
    \${SUBDIR_SOURCES}
    )

target_link_libraries(test_server PUBLIC tls server crypto kyber \${OPENSSL_LIBRARIES})
EOF

mkdir -p build
cd build
cmake .. && make || { echo "Compile failed."; exit 1; }
cd - 

trap 'kill $PROXY_SERVER_PID $SERVER_PID; exit' INT

gunicorn -b localhost:8080 -w 4 --threads=10 --keep-alive 10 server:app --access-logfile access.log --error-logfile error.log &
SERVER_PID=$!
(cd build && ./test_server) &
PROXY_SERVER_PID=$!

wait